Проектная работа. МБОУ АЛГОСОШ им. Фибоначчи
julfy-bs/algososh pull request #1
Opened 2023-08-17 10:33 UTC by julfy-bs

2023-08-17 12:01 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Была проделана огромная работа 🔥.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы все алгоритмы.

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE;

- у вас есть константы для таймингов, они лежат в папки `constants`, используйте их.

- Стек:

  - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. А у вас лоадер отображается на всех кнопках.

- Очередь:

  - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. А у вас лоадер отображается на всех кнопках.

- Связный список:

  - При добавлении/удалении элемента по индексу, анимация должна выполнятся поэтапно. Советую ещё раз ознакомится с заданием на проект, там всё описано. <https://disk.yandex.com/i/t7C-rdxk175aYQ>. У вас удаление происходит не поэтапно.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален;

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/fibonacci-page/utils/startFibonacciAlgorithm.ts
> +};
**Можно лучше:**

Эту функцию лучше сделать в компоненте, тогда не придётся дополнительно передавать сеттеры.

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          max={ 19 }
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/fibonacci-page/utils/createFibonacciArray.ts
> +export const createFibonacciArray = (n: number): number[] => {
**Надо исправить:**

Лучше написать название функции в соответствии с чек-листом `getFibonacciNumbers`.

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +            maxLength={ 4 }
**Надо исправить:**

Здесь и далее.

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +                  key={ nanoid() }
**Можно лучше:**

не рекомендую использовать в качестве key генерируемое значение, т.к. это вызывает перерисовку элемента.

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/fibonacci-page/utils/startFibonacciAlgorithm.ts
> +    await sleep(1000);
**Надо исправить:**

у вас есть константы для таймингов, они лежат в папки constants, используйте их.

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    await sleep(500);
**Надо исправить:**

Здесь и далее.

у вас есть константы для таймингов, они лежат в папки constants, используйте их.

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/queue-page/queue-page.tsx
> +    await sleep(1000);
**Надо исправить:**

Здесь и далее.

у вас есть константы для таймингов, они лежат в папки constants, используйте их.

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/sorting-page/utils/startSorting.ts
> +    await sleep(400);
**Надо исправить:**

Здесь и далее.

у вас есть константы для таймингов, они лежат в папки constants, используйте их.

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/stack-page/stack-page.tsx
> +    await sleep(1000);
**Надо исправить:**

Здесь и далее.

у вас есть константы для таймингов, они лежат в папки constants, используйте их.

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/queue-page/queue-page.tsx
> +            maxLength={ 4 }
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/sorting-page/utils/createRandomArray.ts
> +                             maxLength = 17,
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/stack-page/stack-page.tsx
> +            maxLength={ 4 }
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE

2023-08-17 12:01 UTC, ArslanMustafin commented on src/components/string-page/string-page.tsx
> +          maxLength={ 11 }
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE

2023-08-18 12:07 UTC, julfy-bs commented
Не смог отловить ни одну из перечисленных ниже ошибок. Все работает так, как указано в ТЗ.

1. Стек:

По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. А у вас лоадер отображается на всех кнопках.

2. Очередь:

По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. А у вас лоадер отображается на всех кнопках.

3. Связный список:

При добавлении/удалении элемента по индексу, анимация должна выполнятся поэтапно. Советую ещё раз ознакомится с заданием на проект, там всё описано. [disk.yandex.com/i/t7C-rdxk175aYQ](https://disk.yandex.com/i/t7C-rdxk175aYQ). У вас удаление происходит не поэтапно.

2023-08-18 17:15 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа!)

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-08-18 17:16 UTC, ArslanMustafin commented
> Не смог отловить ни одну из перечисленных ниже ошибок. Все работает так, как указано в ТЗ.
> 
> 1. Стек:
> 
> По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. А у вас лоадер отображается на всех кнопках.
> 
> 2. Очередь:
> 
> По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма. А у вас лоадер отображается на всех кнопках.
> 
> 3. Связный список:
> 
> При добавлении/удалении элемента по индексу, анимация должна выполнятся поэтапно. Советую ещё раз ознакомится с заданием на проект, там всё описано. [disk.yandex.com/i/t7C-rdxk175aYQ](https://disk.yandex.com/i/t7C-rdxk175aYQ). У вас удаление происходит не поэтапно.

Пересмотрел, да действительно все работает так как надо)))

2023-08-24 20:58 UTC, merged